### ISSUE TITLE
Unable to locate module 'opennebula'

### ISSUE THREAD

**Issue by AlbinoGeek** [OpenNebula/addon-nodejs#2]
When attempting to load this NPM module through Meteor.JS and meteorhacks:npm , I receive the following error message: "Error: Unable to locate module 'opennebula'".

The module is installed both locally (app/public/node_modules) as well as globally (/usr/lib/node_modules) as per the norm with ' npm install ' and ' npm -g install ' both.

It is worth noting the directory structure is COMPLETELY DIFFERENT than that of this GIT directory, when installed via the ` npm ` of the latest Node, perhaps there is something wrong h ere?

````
fox2 app # ls public/node_modules/opennebula/
./  ../  lib/  node_modules/  .npmignore  package.json  README.md  test/
````

**Comment by AlbinoGeek** [comment]
Some more information (stack trace for example):

````
I20150222-00:35:08.313(-5)?     at Function.Module._resolveFilename (module.js:338:15)
I20150222-00:35:08.313(-5)?     at Function.Module._load (module.js:280:25)
I20150222-00:35:08.314(-5)?     at Module.require (module.js:364:17)
I20150222-00:35:08.312(-5)? Exception while invoking method 'onLoad' Error: Cannot find module '/root/app/.meteor/local/build/programs/server/npm/npm-container/node_modules/opennebula'
I20150222-00:35:08.314(-5)?     at require (module.js:380:17)
I20150222-00:35:08.314(-5)?     at Object.Npm.require (/root/app/.meteor/local/build/programs/server/boot.js:136:18)
I20150222-00:35:08.314(-5)?     at Object.Meteor.npmRequire (packages/npm-container/index.js:2:1)
I20150222-00:35:08.314(-5)?     at [object Object].onLoad (app/server/__main__.js:6:31)
I20150222-00:35:08.314(-5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
I20150222-00:35:08.315(-5)?     at packages/ddp/livedata_server.js:648:1
I20150222-00:35:08.315(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
````

And again, an `ls` of the directory shows:

````
fox2 app # ls .meteor/local/build/programs/server/npm/npm-container/node_modules/opennebula
./  ../  lib/  node_modules/  .npmignore  package.json  README.md  test/
````

**Comment by AlbinoGeek** [comment]
https://github.com/OpenNebula/addon-nodejs/pull/3

**Comment by apocas** [comment]
Why do you say it's completely different?

As you metioned: 
fox2 app # ls public/node_modules/opennebula/
./  ../  lib/  node_modules/  .npmignore  package.json  README.md  test/

node_modules is obviously created in install, that .npmignore suspect something dynamic on your side.
Basically is exactly the same as in here. O.o
